### ISSUE TITLE
Set server when using appendScriptTag: true

### ISSUE THREAD

**Issue by docmattman** [statianzo/webpack-livereload-plugin#18]
Is there an option to set the server when using the `appendScriptTag: true` option?  I need to use an IP address instead of `localhost`.  I can work around this by not using the the `appendScriptTag` option and setting the ip address in my own script tag, but it'd be ideal if I didn't need to do the work around.

Edit:  After looking at the code, it looks like you could make this an option by replacing

```
this.hostname = this.hostname || 'localhost';
```

With this:

```
this.hostname = this.options.hostname || 'localhost';
```

**Comment by statianzo** [comment]
Looks like a bug. Care to submit a pull request?

**Comment by docmattman** [comment]
Done
