### ISSUE TITLE
Requesting https server

### ISSUE THREAD

**Issue by ramakay** [statianzo/webpack-livereload-plugin#20]
Looks like this might be achieved by creating a httpserver vs httpserver...thoughts?

**Comment by statianzo** [comment]
If you set `key`, `cert`, or `pfx` options, they'll get passed through to [tiny-lr as options](https://github.com/mklabs/tiny-lr#options) and it will serve https. You'll need to also leave `appendScriptTag` as false and manually add a script tag to your html:

```html
<script src="https://localhost:port/livereload.js"></script>
```

**Comment by ramakay** [comment]
Thank you, will give it a try.
