### ISSUE TITLE
Plugin dependencies... 

### ISSUE THREAD

**Issue by nemanjan00** [statianzo/webpack-livereload-plugin#21]
When a plugin uses loader and loader adds dependencies, webpack starts watching files and rebuilds files, but, livereload does not work... 

Plugin: https://github.com/ampedandwired/html-webpack-plugin
Loader I am using: https://github.com/nemanjan00/ejs-compiled-loader/tree/1.x

**Comment by statianzo** [comment]
Can you share a webpack.config.js with this issue?

**Comment by nemanjan00** [comment]
```js
var LiveReloadPlugin = require('webpack-livereload-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
	entry: "./entry.js",
	output: {
		path: __dirname+"/public/assets",
		publicPath: "assets/",
		filename: "bundle.js"
	},
	module: {
		loaders: [
			{
				test: /\.css$/,
				loader: "style-loader!css-loader"
			},
			{
				test : /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
				loader : 'file-loader'
			},
			{
				test: /\.ejs$/,
				loader: "ejs-compiled-loader?ejsify"
			}
		]
	},
	plugins: [
		new LiveReloadPlugin(),
		new HtmlWebpackPlugin({
			filename: '../index.html',
			template: 'index.ejs',
			inject: false
		})
	],
	target: "node-webkit"
};
```

**Comment by nemanjan00** [comment]
Note: if I add 

```js
require('index.ejs');
```

to entry.js, livereload will work... But, I do not need index.ejs there, so, it is just a hack...

**Comment by statianzo** [comment]
What about if you use LiveReloadPlugin with `new LiveReloadPlugin({appendScriptTag: true})`?

**Comment by nemanjan00** [comment]
Nothing changes... Maybe I wasn't clear... Sorry... 
Livereload works for changes on some files, but not those required by plugin... 

If I change files required by entry.js, it works, but for files required by index.ejs, webpack detect changes but livereload does not work...
