### ISSUE TITLE
Load livereload.js over https

### ISSUE THREAD

**Issue by thataustin** [statianzo/webpack-livereload-plugin#23]
I'm in a situation where my local dev server needs to be served over https (for a salesforce plugin).

So, my page won't allow me to load `<script src="http://localhost:35729/livereload.js"></script>` over http, and if I switch that src url to https, the livereload server responds with a ERR_CONNECTION_CLOSED.

I'm not sure if that issue belongs here or not, but I'm curious if you have any ideas for a workaround?

**Comment by statianzo** [comment]
See #20 and see if those steps work for you

**Comment by thataustin** [comment]
Boss.  That worked, thanks a million!

**Comment by statianzo** [comment]
Glad to hear. I've added the instructions to the readme for future users wanting HTTPS.

**Comment by thataustin** [comment]
Good thinking, I imagine that will only pop up more in the future given the proliferation of both https and your tool.

**Comment by asos-hutber** [comment]
@thataustin how on earth did you fix this then? #20 didn't help me much. :dancing_men:
