### ISSUE TITLE
is it possible to delay live reload?

### ISSUE THREAD

**Issue by csakis** [statianzo/webpack-livereload-plugin#25]
I am using a custom webserver for webpack, Whenever I modify my source files, my IDE needs 2-3 seconds to build the project 
I would like to have an option {delay: 3000 } in live-reload so that my browser can refresh after a given amount of time.

**Comment by statianzo** [comment]
You should ask about this in the [tiny-lr project](https://github.com/mklabs/tiny-lr). If something is available as an option on tiny-lr, you can pass it through as an option to webpack-livereload-plugin.

**Comment by csakis** [comment]
I'll try.

**Comment by gwely** [comment]
@csakis did you ever find a solution for this? I am having the same issue - my build system copies the built js files to another directory and the html page references that destination dir. 

```
    plugins: require('./common/plugins').concat([
        new WebpackShellPlugin({
            onBuildExit: [
                'xcopy dist\\* ..\\Scripts\\dist\\ /i/v/y'
            ]
        }),
        new LiveReloadPlugin({
            pfx: fs.readFileSync('./webpack/https/cert.pfx'),
            passphrase: '1234'
        })
    ])
```

The live reload seems to fire before the files have been copied. If I point the script src at the source dir, everything works fine.

**Comment by csakis** [comment]
I use PrePros and that can do the delay for me
