### ISSUE TITLE
Use get-port to find a free port

### ISSUE THREAD

**Issue by rstacruz** [statianzo/webpack-livereload-plugin#27]
https://www.npmjs.com/package/get-port

Instead of hard-coding the LiveReload port, you can find a free port in the system. Unfortunately, get-port is async so it's not straight-forward to implement.

**Comment by statianzo** [comment]
`LiveReloadPlugin.prototype.start` is async, so it wouldn't be terribly difficult to add. If you're interested in taking it on, I'd be happy to review a pull request.
