### ISSUE TITLE
Hot Module Replacement

### ISSUE THREAD

**Issue by jgf5013** [statianzo/webpack-livereload-plugin#32]
This is exactly what I was looking for and was super-easy to setup/configure but my end-goal is to be able to do hot module replacement with a react app. Is that possible with this plugin?

**Comment by statianzo** [comment]
Currently, hot module replacement is not provided by this plugin. I would recommend seeing if you can use `webpack-dev-server` for that functionality.

**Comment by jgf5013** [comment]
Thanks for the quick response. Closing issue.
