### ISSUE TITLE
npm ERR! Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MADPT** [statianzo/webpack-livereload-plugin#34]
Hello github'ers,

When I try to install this plugin by running `npm install webpack-livereload-plugin --save-dev`, I get this warning and error:

```
npm WARN ajv-keywords@1.5.1 requires a peer of ajv@>=4.10.0 but none was installed.
npm ERR! Cannot read property '0' of undefined
```

Do you have any idea why? Here're all packages that I'm using:
```
"auto-prefixer": "^0.4.2",
"autoprefixer": "^7.1.2",
"babel-core": "^6.25.0",
"babel-loader": "^7.1.1",
"babel-preset-es2015": "^6.24.1",
"babel-preset-stage-0": "^6.24.1",
"css-loader": "^0.28.4",
"eslint": "^4.3.0",
"eslint-config-google": "^0.9.1",
"eslint-loader": "^1.9.0",
"extract-text-webpack-plugin": "^3.0.0",
"file-loader": "^0.11.2",
"html-webpack-plugin": "^2.29.0",
"modernizr": "^3.5.0",
"modernizr-loader": "^1.0.1",
"node-sass": "^4.5.3",
"postcss-loader": "^2.0.6",
"rimraf": "^2.6.1",
"sass-loader": "^6.0.6",
"style-loader": "^0.18.2",
"url-loader": "^0.5.9",
"webpack": "^3.4.0",
"webpack-svgstore-plugin": "^4.0.1"
```

Thank you in advance

**Comment by statianzo** [comment]
An npm-debug.log file should've been created after the error. Can you post that?

**Comment by MADPT** [comment]
Sure, you can find it attached (too long to post it directly here)
[npm-debug-log.txt](https://github.com/statianzo/webpack-livereload-plugin/files/1183809/npm-debug-log.txt)

**Comment by statianzo** [comment]
Looks like the error is happening inside of npm code on this line when attempting to unbuild `block-stream`.
https://github.com/npm/npm/blob/release-next/lib/unbuild.js#L61

I'd suggest filing a ticket with this log to https://github.com/npm/npm

**Comment by statianzo** [comment]
Looks like there's already an issue posted for the error. Maybe just attach your log there. https://github.com/npm/npm/issues/17987

**Comment by MADPT** [comment]
~Will do~ Done (https://github.com/npm/npm/issues/18042). Thank you @statianzo

**Comment by MADPT** [comment]
Based on this [comment](https://github.com/npm/npm/issues/17858#issuecomment-318783534), I've found the solution to this problem.

I've deleted the `node_modules` folder and the `package-lock.json` and problem solved.

Once again, thank you for the support @statianzo

**Comment by nagaraj-a** [comment]
rimraf node_modules and npm install solved the problem
