### ISSUE TITLE
How to watch for changes in external files?

### ISSUE THREAD

**Issue by francoisromain** [statianzo/webpack-livereload-plugin#36]
Hello
I installed the plugin which works perfectly when a file is modified in the dependency graph. 
Now, is it possible to also watch and reload the page when other files are modified? (for example php files) 
Thank you

**Comment by francoisromain** [comment]
Ok I found a solution with the [npm livereload](https://www.npmjs.com/package/livereload). package.

**Comment by Brugman** [comment]
@francoisromain I'm facing the same problem: I want to refresh the page not just when I update my CSS and JS, but also the PHP. What exactly was your solution? Replace webpack-livereload-plugin with livereload?

**Comment by francoisromain** [comment]
@Brugman yes exactly.

example npm scripts: 

```
"webpack": "NODE_ENV=dev webpack --watch --progress --colors --display-error-details",
"dev": "npm run webpack & livereload"
```
