### ISSUE TITLE
v1.1.0 doesn't seem to have the `delay` option

### ISSUE THREAD

**Issue by ciampo** [statianzo/webpack-livereload-plugin#47]
Hello,

I just downloaded `webpack-livereload-plugin@1.1.0`, and I was under the impression that this version had the `delay` option available, but it doesn't seem to be there.

Is this on purpose?

Thanks

**Comment by statianzo** [comment]
Thanks for the report. I missed it when splitting versions. Fixed by #46 and published as 1.2.0
