### ISSUE TITLE
Running app behind proxy returns "tinylr": "welcome" message, not expected dist/index,html file

### ISSUE THREAD

**Issue by laurencefass** [statianzo/webpack-livereload-plugin#56]
im trying to live reload an app I have working behind an nginx reverse proxy which routes a public domain/path into a private ip:port used which Im using to configure this module in webpack.config.js file. I've created a template for my index file. 

When run webpack --watch and I load the page all i see is:

{
"tinylr": "Welcome",
"version": "1.1.1"
}

I have added the livereload script into the template which is used to create my index.html file but I don't really understand how the plugin knows which file to use for its entry point. 

**webpack.config.js**

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
var LiveReloadPlugin = require('webpack-livereload-plugin');

module.exports = {
    target: 'node',
    mode: 'development',
    devtool: 'inline-source-map',
    entry: {
        index: './src/index.js',
    },
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
    plugins: [
        new LiveReloadPlugin({
            hostname: '0.0.0.0',
            port: 3803,
            protocol: 'http'
        }),
        new HtmlWebpackPlugin({
            title: 'Development',
            template: 'src/index.template.html'
        }),
    ],
```

This is the file I need to load but Im not specifying it anywhere:

**index.template.html (outputs to dist/index.html)**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Development</title>
  </head>
  <body>
    <script src="http://socket.syntapse.co.uk/chat3/livereload.js"></script>      
    This file is generated by template file /src/index.template.html according to webpack.config.js 
  </body>
</html>

```

**package.json**

```
{
  "name": "webpack watch",
  "version": "0.0.1",
  "description": "super simple webpack watch example",
  "dependencies": {
    "express": "^4.15.2",
    "socket.io": "^1.7.3"
  },
  "scripts": {
    "build": "webpack",
    "watch": "webpack --watch"
  },
  "devDependencies": {
    "webpack-livereload-plugin": "^2.2.0",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.17.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.10.1"
  }
}
```

**nginx.conf server block re routes to webpack.config.js values**

```
server {
    listen 80;
    server_name socket.syntapse.co.uk;
    location ^~ /chat3/ {
        proxy_pass http://0.0.0.0:3803/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

```

any advice or support very much appreciated.

thanks

**Comment by statianzo** [comment]
You're proxying everything to the tinylr server, which only has the purpose of sending live reloads, not sending assets. You've got two options:

* You'll need nginx to serve the static assets and proxy only the live reload connection
* Use something like [webpack-dev-server](https://github.com/webpack/webpack-dev-server) that handles both serving assets and live reloads and proxy over that

**Comment by laurencefass** [comment]
thanks for your advice i will give it a try.

**Comment by laurencefass** [comment]
before i close may i ask question:  I want to live-reload an express app serving html serving html files. This module looks like a far simpler solution than wds for my use-case. I am be grateful for any advice or opinion you have on the most economical solution to live reload express serving html.

**Comment by statianzo** [comment]
If you already have an express app, [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) and [webpack-hot-middleware](https://github.com/webpack-contrib/webpack-hot-middleware) could work as well.

**Comment by laurencefass** [comment]
i think this module is simpler for my needs as I just want to recompile on ANY change to js and html and update the reload the entire page (no HMR necessary yet). Im using a two stage run process... **npm run start** then **npm run watch**.

**package.json**

```
  "scripts": {
    "start": "PORT=3803 node index.js",
    "watch": "webpack --watch --progress"
  },
```

the livereload is running on a different port and im using htmlwebpack plugin to recompile html. I can see that saving either my express file or my html file are both triggering recompilation. 

webpack.config.js

```
    plugins: [
        new HtmlWebpackPlugin({
            title: 'Development',
            template: './index.html'
        }),
        new LiveReloadPlugin({
            hostname: '0.0.0.0',
            port: 3804,
            protocol: 'http'
        })
    ]
```

I can see the compilation but the live reload doesnt appear to be working. google dev tools shows the connection appears ok.

live chat server running at https://socket.syntapse.co.uk/chat3. confirms the express app is serving the html correctly and livereload socket is active.

 





 



m using two stage npm run process.
