### ISSUE TITLE
Support reverse proxied URLs with "public_host" and "public_port" plugin configuration.

### ISSUE THREAD

**Issue by laurencefass** [statianzo/webpack-livereload-plugin#57]
I am running an express server and a separate webpack instance to watch for code changes. I am using a reverse proxy to route public-domain/path URL to host:port addresses for my server and my webpack (livereload) instance. I think the plugin doesn't support reverse proxied public URL's due to missing configuration but I'm very happy to be corrected if i'm not using the plugin correctly.

live server here: https://socket.syntapse.co.uk/chat3. Reload the page and check developer tools for the errors.

Preliminaries: I run "npm run start" and "npm run watch" on my server and the express app serves the page and loads livereload.js as expected.

Issue: Webpack is recompiling code but livereload.js throws an error and live reload fails:

**error:**  

"WebSocket connection to 'ws://socket.syntapse.co.uk:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED"

problem:

socket.syntapse.co.uk:35729 is not a valid address. my livereload server is running socket.syntapse.co.uk/chat3:80 but i have no way to configure the livereload plugin to know this.

**probable causes:** 

1. The websocket address format in livereload.js does not support proxy configurations.
2. The options.port is incorrect and doesn't match my plugin configuration. It looks like the default value is being used.

**possible fix**

I think 'socket.syntapse.co.uk:35729/livereload' should become 'socket.syntapse.co.uk/chat3/livereload for correct reverse proxying. To support reverse proxy configurations add a public_host and public_port setting to the livereload plugin config. Use these values to construct the URL in the livereload.js file if they exist else resort to currently supported host and port values. If the port is not included omit it entirely to support the domain.com/path to host:port configuration requirements of a reverse proxied server.

this same functionality exists in the webpack-dev-server to cover the same use case.

**My configuration**

app public URL:

```
https://socket.syntapse.co.uk/chat3

```

**<script> to load livereload.js in my express served index.html file**

```
<script src="https://socket.syntapse.co.uk/chat3/livereload/livereload.js"></script>
```

**package.json**

```
  "scripts": {
    "start": "PORT=3803 node index.js",
    "watch": "webpack --watch --progress"
  },
```

webpack.config.js

```
    plugins: [
        new HtmlWebpackPlugin({
            title: 'Development',
            template: './index.html'
        }),
        new LiveReloadPlugin({
            hostname: '0.0.0.0',
            port: 3804,
            protocol: 'http'
        })
    ]
```

**nginx routes my public URLs to host:port**

```
    location ^~ /chat3/livereload/ {
        proxy_pass http://0.0.0.0:3804/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location ^~ /chat3/socket.io/ {
        proxy_pass http://0.0.0.0:3803/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }    
    location ^~ /chat3/ {
        proxy_pass http://0.0.0.0:3803/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

note: please ignore the 404 error on call to index.js. This is only included in the htmlplugin output so i can trigger a recompilation on save.

**Comment by statianzo** [comment]
You can configure options of the livereload.js file via the querystring in the script tag:

```html
<script src="https://socket.syntapse.co.uk/chat3/livereload/livereload.js?port=80&path=/chat3/livereload"></script>
```

See https://github.com/livereload/livereload-js#options

**Comment by laurencefass** [comment]
thanks very much i will try it out.

**Comment by laurencefass** [comment]
This clears the above issue but now receiving SSL protocol error and insecure page.  

WebSocket connection to 'wss://socket.syntapse.co.uk:80/chat3/livereload' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR. 

I realise configuring my proxies is out of scope but is there way to use polling instead. In this example the chat socket is polling and I havent worked out how to route the wss://. 

Is there a way to configure lr.js to select polling on the client instead of connection through  wss://?
