### ISSUE TITLE
hot-update files created in output dir

### ISSUE THREAD

**Issue by dmachat** [statianzo/webpack-livereload-plugin#6]
Before I look into this, any chance you know how/why the updated modules would get output? My outdir dir look like this after a new watch compilation:
```
-rw-r--r-- 1 drew users 1596 Sep 25 14:23 0.1f74233156bb2b1f7cb2.hot-update.js
-rw-r--r-- 1 drew users 1831 Sep 25 14:23 0.1f74233156bb2b1f7cb2.hot-update.js.map
-rw-r--r-- 1 drew users   36 Sep 25 14:23 1f74233156bb2b1f7cb2.hot-update.json
```
I'm just gitignoring these for now, but ideally they should emit to tmp or get cleaned up automatically.

**Comment by statianzo** [comment]
I'm not sure. I haven't used the hot module reloading.

**Comment by dmachat** [comment]
Yeah, that's what's weird. I don't have HMR turned on.

**Comment by statianzo** [comment]
Does it appear when this plugin isn't enabled?

**Comment by dmachat** [comment]
Ugh, a stupid one, sorry. `-watch` vs `--watch` makes a big difference if you only want watch turned on :blush:
