### ISSUE TITLE
TypeError: compiler.plugin is not a function (Webpack 5 plugin API change)

### ISSUE THREAD

**Issue by deltork** [statianzo/webpack-livereload-plugin#74]
Webpack 5 has changed the API for the plugin interface ( similar issue https://github.com/webpack/webpack/issues/11672).
Therefore when I try to use this plugin, I get this error
`[webpack-cli] TypeError: compiler.plugin is not a function
    at LiveReloadPlugin.apply (node_modules\webpack-livereload-plugin\index.js:110:12)
`

**Comment by statianzo** [comment]
@deltork that error on that line number refers to 1.x version of this plugin designed for webpack 2. Upgrade to the latest and try again.
